#./emsdk activate latest
#source ./emsdk_env.sh
#emcc --bind -o ../../Web\ Application/ga.js gacplus.cpp Evaluate.cpp GA.cpp Individual.cpp Population.cpp Utils.cpp
#emrun ../../Web\ Application/index.html --port 8000
g++ -o Build/ga.exe gacplus.cpp Evaluate.cpp GA.cpp Individual.cpp Population.cpp Utils.cpp